##################################################################################
# Use this file to customize helm chart behavior
# Please make sure your custom changes doesn't conflict with values.yaml
##################################################################################

utilities:
  image:
    tag: v2.1.0-beta

ingress:
  admin_console_allowlist:
    - 49.12.218.32/32