##################################################################################
# Use this file to customize helm chart behavior
# Please make sure your custom changes doesn't conflict with values.yaml
##################################################################################

utilities:
  image:
    tag: v2.1.0-beta

network_policies:
  ingress_mode: deny
  egress_mode: deny
  allowed_namespaces:
    - opencrvs-perftest